rawlings-demo/force-app/main/default/objects/Lien__c/Lien__c.object-meta.xml
<CustomObject>
    <label>Lien</label>
    <pluralLabel>Liens</pluralLabel>
    <nameField>
        <label>Lien Name</label>
        <type>AutoNumber</type>
        <displayFormat>LN-{0000}</displayFormat>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

rawlings-demo/force-app/main/default/objects/Lien__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <label>Settlement</label>
    <type>Lookup</type>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Liens</relationshipLabel>
    <relationshipName>Liens</relationshipName>
    <required>true</required>
    <deleteConstraint>Cascade</deleteConstraint>
</CustomField>

rawlings-demo/force-app/main/default/objects/Lien__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
                <default>true</default>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Coverage Confirmed</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Response Ready</fullName>
            </value>
            <value>
                <fullName>Response Submitted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Agreed</fullName>
            </value>
            <value>
                <fullName>Pre-Validation</fullName>
            </value>
            <value>
                <fullName>Recovery Calculated</fullName>
            </value>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

rawlings-demo/force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <label>Settlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

rawlings-demo/force-app/main/default/classes/LienBulkStageTransitionBatch.cls
public with sharing class LienBulkStageTransitionBatch implements Database.Batchable<SObject> {

    private Id settlementId;
    private String fromStage;
    private String toStage;

    public LienBulkStageTransitionBatch(Id settlementId, String fromStage, String toStage) {
        this.settlementId = settlementId;
        this.fromStage = fromStage;
        this.toStage = toStage;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Stage__c
            FROM Lien__c
            WHERE Settlement__c = :settlementId
            AND Stage__c = :fromStage
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Lien__c> scope) {
        for (Lien__c lien : scope) {
            lien.Stage__c = toStage;
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {
    }
}